import { FormStep } from '@/types/insurance';

const commonSteps: FormStep[] = [
  {
    id: 'company-info',
    title: 'Company Information',
    description: 'Tell us about your business',
    fields: [
      {
        name: 'companyInfo.legalName',
        label: 'Legal Business Name',
        type: 'text',
        required: true,
        placeholder: 'Acme Corporation',
      },
      {
        name: 'companyInfo.dba',
        label: 'Doing Business As (DBA)',
        type: 'text',
        required: false,
        placeholder: 'Optional if different from legal name',
      },
      {
        name: 'companyInfo.federalTaxId',
        label: 'Federal Tax ID (EIN)',
        type: 'text',
        required: true,
        placeholder: 'XX-XXXXXXX',
        helperText: 'Your 9-digit Employer Identification Number',
        validation: {
          pattern: String.raw`^\d{2}-?\d{7}$`,
          patternMessage: 'Please enter a valid EIN (XX-XXXXXXX)',
        },
      },
      {
        name: 'companyInfo.businessStructure',
        label: 'Business Structure',
        type: 'select',
        required: true,
        options: [
          { value: 'llc', label: 'Limited Liability Company (LLC)' },
          { value: 'corporation', label: 'C Corporation' },
          { value: 's-corp', label: 'S Corporation' },
          { value: 'partnership', label: 'Partnership' },
          { value: 'lp', label: 'Limited Partnership (LP)' },
          { value: 'llp', label: 'Limited Liability Partnership (LLP)' },
          { value: 'sole-proprietorship', label: 'Sole Proprietorship' },
          { value: 'nonprofit', label: 'Non-Profit Organization' },
          { value: 'other', label: 'Other' },
        ],
      },
      {
        name: 'companyInfo.stateOfIncorporation',
        label: 'State of Incorporation',
        type: 'select',
        required: true,
        options: [
          { value: 'AL', label: 'Alabama' },
          { value: 'AK', label: 'Alaska' },
          { value: 'AZ', label: 'Arizona' },
          { value: 'AR', label: 'Arkansas' },
          { value: 'CA', label: 'California' },
          { value: 'CO', label: 'Colorado' },
          { value: 'CT', label: 'Connecticut' },
          { value: 'DE', label: 'Delaware' },
          { value: 'FL', label: 'Florida' },
          { value: 'GA', label: 'Georgia' },
          { value: 'HI', label: 'Hawaii' },
          { value: 'ID', label: 'Idaho' },
          { value: 'IL', label: 'Illinois' },
          { value: 'IN', label: 'Indiana' },
          { value: 'IA', label: 'Iowa' },
          { value: 'KS', label: 'Kansas' },
          { value: 'KY', label: 'Kentucky' },
          { value: 'LA', label: 'Louisiana' },
          { value: 'ME', label: 'Maine' },
          { value: 'MD', label: 'Maryland' },
          { value: 'MA', label: 'Massachusetts' },
          { value: 'MI', label: 'Michigan' },
          { value: 'MN', label: 'Minnesota' },
          { value: 'MS', label: 'Mississippi' },
          { value: 'MO', label: 'Missouri' },
          { value: 'MT', label: 'Montana' },
          { value: 'NE', label: 'Nebraska' },
          { value: 'NV', label: 'Nevada' },
          { value: 'NH', label: 'New Hampshire' },
          { value: 'NJ', label: 'New Jersey' },
          { value: 'NM', label: 'New Mexico' },
          { value: 'NY', label: 'New York' },
          { value: 'NC', label: 'North Carolina' },
          { value: 'ND', label: 'North Dakota' },
          { value: 'OH', label: 'Ohio' },
          { value: 'OK', label: 'Oklahoma' },
          { value: 'OR', label: 'Oregon' },
          { value: 'PA', label: 'Pennsylvania' },
          { value: 'RI', label: 'Rhode Island' },
          { value: 'SC', label: 'South Carolina' },
          { value: 'SD', label: 'South Dakota' },
          { value: 'TN', label: 'Tennessee' },
          { value: 'TX', label: 'Texas' },
          { value: 'UT', label: 'Utah' },
          { value: 'VT', label: 'Vermont' },
          { value: 'VA', label: 'Virginia' },
          { value: 'WA', label: 'Washington' },
          { value: 'WV', label: 'West Virginia' },
          { value: 'WI', label: 'Wisconsin' },
          { value: 'WY', label: 'Wyoming' },
          { value: 'DC', label: 'District of Columbia' },
        ],
      },
      {
        name: 'companyInfo.yearEstablished',
        label: 'Year Established',
        type: 'number',
        required: true,
        placeholder: '2020',
        validation: {
          min: 1900,
          max: new Date().getFullYear(),
        },
      },
      {
        name: 'companyInfo.website',
        label: 'Company Website',
        type: 'text',
        required: true,
        placeholder: 'https://www.example.com',
      },
    ],
  },
  {
    id: 'business-details',
    title: 'Business Details',
    description: 'Tell us more about your operations',
    fields: [
      {
        name: 'companyInfo.naicsCode',
        label: 'NAICS Code (if known)',
        type: 'text',
        required: false,
        placeholder: '541511',
        helperText: 'North American Industry Classification System code',
      },
      {
        name: 'companyInfo.industry',
        label: 'Primary Industry',
        type: 'select',
        required: true,
        options: [
          { value: 'technology', label: 'Technology / Software' },
          { value: 'consulting', label: 'Consulting / Professional Services' },
          { value: 'healthcare', label: 'Healthcare / Medical' },
          { value: 'finance', label: 'Finance / Banking' },
          { value: 'manufacturing', label: 'Manufacturing' },
          { value: 'retail', label: 'Retail / E-commerce' },
          { value: 'construction', label: 'Construction' },
          { value: 'realestate', label: 'Real Estate' },
          { value: 'education', label: 'Education' },
          { value: 'hospitality', label: 'Hospitality / Food Service' },
          { value: 'transportation', label: 'Transportation / Logistics' },
          { value: 'media', label: 'Media / Entertainment' },
          { value: 'nonprofit', label: 'Non-Profit' },
          { value: 'other', label: 'Other' },
        ],
      },
      {
        name: 'companyInfo.description',
        label: 'Detailed Business Description',
        type: 'textarea',
        required: true,
        placeholder: 'Describe your company\'s primary business activities, products, and services...',
        helperText: 'Be specific about what your company does. This helps us find the best coverage.',
        validation: {
          minLength: 50,
        },
      },
      {
        name: 'companyInfo.servicesOffered',
        label: 'Primary Services/Products Offered',
        type: 'textarea',
        required: true,
        placeholder: 'List your main services or products...',
      },
    ],
  },
  {
    id: 'financials',
    title: 'Financial Information',
    description: 'Revenue and employee details',
    fields: [
      {
        name: 'companyInfo.annualRevenue',
        label: 'Current Annual Revenue (USD)',
        type: 'currency',
        required: true,
        placeholder: '1000000',
        helperText: 'Enter your current fiscal year revenue',
      },
      {
        name: 'companyInfo.projectedRevenue',
        label: 'Projected Next Year Revenue (USD)',
        type: 'currency',
        required: true,
        placeholder: '1500000',
        helperText: 'Enter your projected revenue for the next 12 months',
      },
      {
        name: 'companyInfo.revenueBreakdown.domestic',
        label: 'Domestic Revenue Percentage',
        type: 'number',
        required: true,
        placeholder: '80',
        helperText: 'Percentage of revenue from US operations',
        validation: {
          min: 0,
          max: 100,
        },
      },
      {
        name: 'companyInfo.revenueBreakdown.international',
        label: 'International Revenue Percentage',
        type: 'number',
        required: true,
        placeholder: '20',
        helperText: 'Percentage of revenue from international operations',
        validation: {
          min: 0,
          max: 100,
        },
      },
      {
        name: 'companyInfo.numberOfEmployees',
        label: 'Total Number of Employees',
        type: 'number',
        required: true,
        placeholder: '25',
      },
      {
        name: 'companyInfo.fullTimeEmployees',
        label: 'Full-Time Employees',
        type: 'number',
        required: true,
        placeholder: '20',
      },
      {
        name: 'companyInfo.partTimeEmployees',
        label: 'Part-Time Employees',
        type: 'number',
        required: false,
        placeholder: '5',
      },
      {
        name: 'companyInfo.contractors',
        label: 'Independent Contractors',
        type: 'number',
        required: false,
        placeholder: '10',
        helperText: '1099 contractors or subcontractors',
      },
    ],
  },
  {
    id: 'address',
    title: 'Business Address',
    description: 'Where is your business located?',
    fields: [
      {
        name: 'companyInfo.address.street',
        label: 'Street Address',
        type: 'text',
        required: true,
        placeholder: '123 Main Street',
      },
      {
        name: 'companyInfo.address.suite',
        label: 'Suite/Unit Number',
        type: 'text',
        required: false,
        placeholder: 'Suite 100',
      },
      {
        name: 'companyInfo.address.city',
        label: 'City',
        type: 'text',
        required: true,
        placeholder: 'New York',
      },
      {
        name: 'companyInfo.address.state',
        label: 'State',
        type: 'select',
        required: true,
        options: [
          { value: 'AL', label: 'Alabama' },
          { value: 'AK', label: 'Alaska' },
          { value: 'AZ', label: 'Arizona' },
          { value: 'AR', label: 'Arkansas' },
          { value: 'CA', label: 'California' },
          { value: 'CO', label: 'Colorado' },
          { value: 'CT', label: 'Connecticut' },
          { value: 'DE', label: 'Delaware' },
          { value: 'FL', label: 'Florida' },
          { value: 'GA', label: 'Georgia' },
          { value: 'HI', label: 'Hawaii' },
          { value: 'ID', label: 'Idaho' },
          { value: 'IL', label: 'Illinois' },
          { value: 'IN', label: 'Indiana' },
          { value: 'IA', label: 'Iowa' },
          { value: 'KS', label: 'Kansas' },
          { value: 'KY', label: 'Kentucky' },
          { value: 'LA', label: 'Louisiana' },
          { value: 'ME', label: 'Maine' },
          { value: 'MD', label: 'Maryland' },
          { value: 'MA', label: 'Massachusetts' },
          { value: 'MI', label: 'Michigan' },
          { value: 'MN', label: 'Minnesota' },
          { value: 'MS', label: 'Mississippi' },
          { value: 'MO', label: 'Missouri' },
          { value: 'MT', label: 'Montana' },
          { value: 'NE', label: 'Nebraska' },
          { value: 'NV', label: 'Nevada' },
          { value: 'NH', label: 'New Hampshire' },
          { value: 'NJ', label: 'New Jersey' },
          { value: 'NM', label: 'New Mexico' },
          { value: 'NY', label: 'New York' },
          { value: 'NC', label: 'North Carolina' },
          { value: 'ND', label: 'North Dakota' },
          { value: 'OH', label: 'Ohio' },
          { value: 'OK', label: 'Oklahoma' },
          { value: 'OR', label: 'Oregon' },
          { value: 'PA', label: 'Pennsylvania' },
          { value: 'RI', label: 'Rhode Island' },
          { value: 'SC', label: 'South Carolina' },
          { value: 'SD', label: 'South Dakota' },
          { value: 'TN', label: 'Tennessee' },
          { value: 'TX', label: 'Texas' },
          { value: 'UT', label: 'Utah' },
          { value: 'VT', label: 'Vermont' },
          { value: 'VA', label: 'Virginia' },
          { value: 'WA', label: 'Washington' },
          { value: 'WV', label: 'West Virginia' },
          { value: 'WI', label: 'Wisconsin' },
          { value: 'WY', label: 'Wyoming' },
          { value: 'DC', label: 'District of Columbia' },
        ],
      },
      {
        name: 'companyInfo.address.zip',
        label: 'ZIP Code',
        type: 'text',
        required: true,
        placeholder: '10001',
        validation: {
          pattern: String.raw`^\d{5}(-\d{4})?$`,
          patternMessage: 'Please enter a valid ZIP code',
        },
      },
      {
        name: 'companyInfo.address.country',
        label: 'Country',
        type: 'select',
        required: true,
        options: [
          { value: 'US', label: 'United States' },
          { value: 'CA', label: 'Canada' },
        ],
      },
      {
        name: 'companyInfo.hasMultipleLocations',
        label: 'Does your company have multiple locations?',
        type: 'radio',
        required: true,
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'no', label: 'No' },
        ],
      },
      {
        name: 'companyInfo.numberOfLocations',
        label: 'Number of Locations',
        type: 'number',
        required: false,
        placeholder: '3',
        helperText: 'If multiple locations, how many total?',
      },
    ],
  },
  {
    id: 'contact',
    title: 'Contact Information',
    description: 'Primary contact for this application',
    fields: [
      {
        name: 'contactInfo.primaryContact.firstName',
        label: 'First Name',
        type: 'text',
        required: true,
        placeholder: 'John',
      },
      {
        name: 'contactInfo.primaryContact.lastName',
        label: 'Last Name',
        type: 'text',
        required: true,
        placeholder: 'Doe',
      },
      {
        name: 'contactInfo.primaryContact.title',
        label: 'Title/Position',
        type: 'text',
        required: true,
        placeholder: 'CEO',
      },
      {
        name: 'contactInfo.primaryContact.email',
        label: 'Email Address',
        type: 'email',
        required: true,
        placeholder: 'john@example.com',
      },
      {
        name: 'contactInfo.primaryContact.phone',
        label: 'Phone Number',
        type: 'tel',
        required: true,
        placeholder: '(555) 123-4567',
      },
      {
        name: 'contactInfo.primaryContact.extension',
        label: 'Extension',
        type: 'text',
        required: false,
        placeholder: '123',
      },
      {
        name: 'contactInfo.alternateContact.hasAlternate',
        label: 'Add Alternate Contact?',
        type: 'radio',
        required: true,
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'no', label: 'No' },
        ],
      },
    ],
  },
  {
    id: 'coverage',
    title: 'Coverage Requirements',
    description: 'What coverage do you need?',
    fields: [
      {
        name: 'coverageDetails.requestedLimits',
        label: 'Requested Coverage Limit',
        type: 'select',
        required: true,
        options: [
          { value: '250000', label: '$250,000' },
          { value: '500000', label: '$500,000' },
          { value: '1000000', label: '$1,000,000' },
          { value: '2000000', label: '$2,000,000' },
          { value: '3000000', label: '$3,000,000' },
          { value: '5000000', label: '$5,000,000' },
          { value: '10000000', label: '$10,000,000' },
          { value: 'other', label: 'Other (specify in comments)' },
        ],
      },
      {
        name: 'coverageDetails.requestedDeductible',
        label: 'Preferred Deductible',
        type: 'select',
        required: true,
        options: [
          { value: '0', label: '$0' },
          { value: '1000', label: '$1,000' },
          { value: '2500', label: '$2,500' },
          { value: '5000', label: '$5,000' },
          { value: '10000', label: '$10,000' },
          { value: '25000', label: '$25,000' },
          { value: '50000', label: '$50,000' },
          { value: '100000', label: '$100,000' },
        ],
      },
      {
        name: 'coverageDetails.effectiveDate',
        label: 'Desired Effective Date',
        type: 'date',
        required: true,
        helperText: 'When do you want coverage to begin?',
      },
      {
        name: 'coverageDetails.expirationDate',
        label: 'Desired Expiration Date',
        type: 'date',
        required: false,
        helperText: 'Leave blank for standard 1-year term',
      },
      {
        name: 'coverageDetails.priorCoverage',
        label: 'Do you currently have this type of coverage?',
        type: 'radio',
        required: true,
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'no', label: 'No' },
        ],
      },
      {
        name: 'coverageDetails.currentCarrier',
        label: 'Current Insurance Carrier (if applicable)',
        type: 'text',
        required: false,
        placeholder: 'e.g., Hartford, Chubb, AIG',
      },
      {
        name: 'coverageDetails.currentPremium',
        label: 'Current Annual Premium (if applicable)',
        type: 'currency',
        required: false,
        placeholder: '5000',
      },
      {
        name: 'coverageDetails.currentPolicyExpiration',
        label: 'Current Policy Expiration Date',
        type: 'date',
        required: false,
      },
      {
        name: 'coverageDetails.reasonForChange',
        label: 'Reason for Seeking New Coverage',
        type: 'select',
        required: false,
        options: [
          { value: 'new-coverage', label: 'First time purchasing this coverage' },
          { value: 'price', label: 'Looking for better pricing' },
          { value: 'service', label: 'Service issues with current carrier' },
          { value: 'coverage-change', label: 'Need different coverage limits' },
          { value: 'renewal', label: 'Policy renewal / shopping around' },
          { value: 'other', label: 'Other' },
        ],
      },
    ],
  },
  {
    id: 'claims-history',
    title: 'Claims History',
    description: 'Tell us about any past claims',
    fields: [
      {
        name: 'coverageDetails.claimsHistory.hasClaimsHistory',
        label: 'Have you had any claims related to this coverage in the past 5 years?',
        type: 'radio',
        required: true,
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'no', label: 'No' },
        ],
      },
      {
        name: 'coverageDetails.claimsHistory.numberOfClaims',
        label: 'Number of Claims',
        type: 'number',
        required: false,
        placeholder: '1',
        helperText: 'If yes, how many claims?',
      },
      {
        name: 'coverageDetails.claimsHistory.claimsDescription',
        label: 'Claims Description',
        type: 'textarea',
        required: false,
        placeholder: 'Please describe each claim including date, amount, and outcome...',
        helperText: 'Provide details for each claim',
      },
      {
        name: 'coverageDetails.claimsHistory.totalClaimsAmount',
        label: 'Total Claims Amount Paid',
        type: 'currency',
        required: false,
        placeholder: '25000',
      },
      {
        name: 'coverageDetails.claimsHistory.pendingClaims',
        label: 'Are there any pending claims or incidents that may give rise to a claim?',
        type: 'radio',
        required: true,
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'no', label: 'No' },
        ],
      },
      {
        name: 'coverageDetails.claimsHistory.pendingDescription',
        label: 'Pending Claims/Incidents Description',
        type: 'textarea',
        required: false,
        placeholder: 'Describe any pending situations...',
      },
      {
        name: 'coverageDetails.claimsHistory.previouslyCancelled',
        label: 'Has any insurer ever cancelled, declined, or non-renewed your coverage?',
        type: 'radio',
        required: true,
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'no', label: 'No' },
        ],
      },
      {
        name: 'coverageDetails.claimsHistory.cancellationDetails',
        label: 'Cancellation/Declination Details',
        type: 'textarea',
        required: false,
        placeholder: 'If yes, please explain...',
      },
    ],
  },
  {
    id: 'review',
    title: 'Review & Submit',
    description: 'Review your application before submitting',
    fields: [
      {
        name: 'additionalInfo.comments',
        label: 'Additional Comments',
        type: 'textarea',
        required: false,
        placeholder: 'Any additional information you\'d like to share...',
      },
      {
        name: 'additionalInfo.referralSource',
        label: 'How did you hear about us?',
        type: 'select',
        required: false,
        options: [
          { value: 'search', label: 'Online Search' },
          { value: 'referral', label: 'Referral' },
          { value: 'social', label: 'Social Media' },
          { value: 'advertisement', label: 'Advertisement' },
          { value: 'event', label: 'Event/Conference' },
          { value: 'other', label: 'Other' },
        ],
      },
      {
        name: 'additionalInfo.agreementTerms',
        label: 'I certify that the information provided is true and accurate to the best of my knowledge',
        type: 'checkbox',
        required: true,
      },
      {
        name: 'additionalInfo.agreementPrivacy',
        label: 'I agree to the Privacy Policy and Terms of Service',
        type: 'checkbox',
        required: true,
      },
      {
        name: 'additionalInfo.contactConsent',
        label: 'I consent to being contacted regarding this application',
        type: 'checkbox',
        required: true,
      },
    ],
  },
];

export { commonSteps };
