import { InsuranceTypeConfig, FormStep } from '@/types/insurance';
import { commonSteps } from './common-steps';

const techEOSpecificSteps: FormStep[] = [
  {
    id: 'tech-products',
    title: 'Products & Services',
    description: 'Tell us about your technology offerings',
    fields: [
      {
        name: 'specificData.productsServices',
        label: 'Detailed Description of Products/Services',
        type: 'textarea',
        required: true,
        placeholder: 'Describe in detail the software, applications, or technology services you provide to clients...',
        helperText: 'Be thorough - this helps underwriters understand your business',
        validation: {
          minLength: 100,
        },
      },
      {
        name: 'specificData.softwareType',
        label: 'Primary Software/Service Type',
        type: 'select',
        required: true,
        options: [
          { value: 'saas', label: 'SaaS (Software as a Service)' },
          { value: 'paas', label: 'PaaS (Platform as a Service)' },
          { value: 'iaas', label: 'IaaS (Infrastructure as a Service)' },
          { value: 'web', label: 'Web Application Development' },
          { value: 'mobile', label: 'Mobile Application Development' },
          { value: 'on-premise', label: 'On-Premise Software' },
          { value: 'embedded', label: 'Embedded Systems/IoT' },
          { value: 'consulting', label: 'IT Consulting Services' },
          { value: 'managed-services', label: 'Managed IT Services' },
          { value: 'system-integration', label: 'System Integration' },
          { value: 'custom-development', label: 'Custom Software Development' },
          { value: 'data-analytics', label: 'Data Analytics/Business Intelligence' },
          { value: 'ai-ml', label: 'AI/Machine Learning Services' },
          { value: 'other', label: 'Other' },
        ],
      },
      {
        name: 'specificData.technologyStack',
        label: 'Technology Stack',
        type: 'textarea',
        required: true,
        placeholder: 'e.g., React, Node.js, Python, AWS, Azure, PostgreSQL...',
        helperText: 'List the main technologies, frameworks, and platforms you use',
      },
      {
        name: 'specificData.clientTypes',
        label: 'Primary Client Types',
        type: 'select',
        required: true,
        options: [
          { value: 'b2b-enterprise', label: 'B2B - Enterprise Clients' },
          { value: 'b2b-smb', label: 'B2B - Small/Medium Businesses' },
          { value: 'b2c', label: 'B2C - Direct Consumers' },
          { value: 'government', label: 'Government/Public Sector' },
          { value: 'healthcare', label: 'Healthcare Organizations' },
          { value: 'financial', label: 'Financial Institutions' },
          { value: 'education', label: 'Educational Institutions' },
          { value: 'mixed', label: 'Mixed Client Base' },
        ],
      },
      {
        name: 'specificData.numberOfClients',
        label: 'Total Number of Active Clients',
        type: 'number',
        required: true,
        placeholder: '50',
      },
      {
        name: 'specificData.largestClientRevenue',
        label: 'Revenue from Largest Client (USD)',
        type: 'currency',
        required: true,
        placeholder: '100000',
        helperText: 'Annual revenue from your largest single client',
      },
      {
        name: 'specificData.largestClientPercentage',
        label: 'Largest Client as % of Total Revenue',
        type: 'number',
        required: true,
        placeholder: '15',
        validation: {
          min: 0,
          max: 100,
        },
      },
    ],
  },
  {
    id: 'tech-operations',
    title: 'Technology Operations',
    description: 'Details about your technology infrastructure',
    fields: [
      {
        name: 'specificData.hostingEnvironment',
        label: 'Primary Hosting Environment',
        type: 'select',
        required: true,
        options: [
          { value: 'aws', label: 'Amazon Web Services (AWS)' },
          { value: 'azure', label: 'Microsoft Azure' },
          { value: 'gcp', label: 'Google Cloud Platform' },
          { value: 'private-cloud', label: 'Private Cloud' },
          { value: 'on-premise', label: 'On-Premise Data Center' },
          { value: 'hybrid', label: 'Hybrid (Cloud + On-Premise)' },
          { value: 'colocation', label: 'Colocation Facility' },
          { value: 'multiple', label: 'Multiple Cloud Providers' },
        ],
      },
      {
        name: 'specificData.hasDisasterRecovery',
        label: 'Do you have a disaster recovery plan?',
        type: 'radio',
        required: true,
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'no', label: 'No' },
        ],
      },
      {
        name: 'specificData.recoveryTimeObjective',
        label: 'Recovery Time Objective (RTO)',
        type: 'select',
        required: false,
        options: [
          { value: 'minutes', label: 'Minutes (< 1 hour)' },
          { value: '1-4-hours', label: '1-4 hours' },
          { value: '4-24-hours', label: '4-24 hours' },
          { value: '1-3-days', label: '1-3 days' },
          { value: '3-plus-days', label: '3+ days' },
          { value: 'unknown', label: 'Not established' },
        ],
        helperText: 'Maximum acceptable downtime after a disaster',
      },
      {
        name: 'specificData.uptimeGuarantee',
        label: 'Uptime/SLA Guarantee to Clients',
        type: 'select',
        required: true,
        options: [
          { value: '99.99', label: '99.99% (Four 9s)' },
          { value: '99.9', label: '99.9% (Three 9s)' },
          { value: '99.5', label: '99.5%' },
          { value: '99', label: '99%' },
          { value: '95', label: '95%' },
          { value: 'none', label: 'No uptime guarantee' },
        ],
      },
      {
        name: 'specificData.hasBackups',
        label: 'Do you maintain regular data backups?',
        type: 'radio',
        required: true,
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'no', label: 'No' },
        ],
      },
      {
        name: 'specificData.backupFrequency',
        label: 'Backup Frequency',
        type: 'select',
        required: false,
        options: [
          { value: 'realtime', label: 'Real-time / Continuous' },
          { value: 'hourly', label: 'Hourly' },
          { value: 'daily', label: 'Daily' },
          { value: 'weekly', label: 'Weekly' },
          { value: 'monthly', label: 'Monthly' },
        ],
      },
    ],
  },
  {
    id: 'data-handling',
    title: 'Data Handling & Privacy',
    description: 'How do you handle client and user data?',
    fields: [
      {
        name: 'specificData.dataHandling.handlesPII',
        label: 'Do you handle Personally Identifiable Information (PII)?',
        type: 'radio',
        required: true,
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'no', label: 'No' },
        ],
      },
      {
        name: 'specificData.dataHandling.piiTypes',
        label: 'Types of PII Handled (select all that apply)',
        type: 'textarea',
        required: false,
        placeholder: 'e.g., Names, Email addresses, Social Security Numbers, Health records, Financial data...',
        helperText: 'List all types of personal data you collect or process',
      },
      {
        name: 'specificData.dataHandling.recordsCount',
        label: 'Approximate Number of Records Containing PII',
        type: 'select',
        required: false,
        options: [
          { value: 'under-1000', label: 'Under 1,000' },
          { value: '1000-10000', label: '1,000 - 10,000' },
          { value: '10000-100000', label: '10,000 - 100,000' },
          { value: '100000-1m', label: '100,000 - 1 Million' },
          { value: '1m-10m', label: '1 Million - 10 Million' },
          { value: 'over-10m', label: 'Over 10 Million' },
        ],
      },
      {
        name: 'specificData.dataHandling.handlesPaymentData',
        label: 'Do you process or store payment/credit card data?',
        type: 'radio',
        required: true,
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'no', label: 'No' },
        ],
      },
      {
        name: 'specificData.dataHandling.pciCompliant',
        label: 'Are you PCI-DSS compliant?',
        type: 'radio',
        required: false,
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'no', label: 'No' },
          { value: 'in-progress', label: 'In Progress' },
          { value: 'na', label: 'Not Applicable' },
        ],
      },
      {
        name: 'specificData.dataHandling.handlesHealthData',
        label: 'Do you handle Protected Health Information (PHI)?',
        type: 'radio',
        required: true,
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'no', label: 'No' },
        ],
      },
      {
        name: 'specificData.dataHandling.hipaaCompliant',
        label: 'Are you HIPAA compliant?',
        type: 'radio',
        required: false,
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'no', label: 'No' },
          { value: 'in-progress', label: 'In Progress' },
          { value: 'na', label: 'Not Applicable' },
        ],
      },
      {
        name: 'specificData.dataHandling.dataEncryptionAtRest',
        label: 'Is sensitive data encrypted at rest?',
        type: 'radio',
        required: true,
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'no', label: 'No' },
          { value: 'partial', label: 'Partially' },
        ],
      },
      {
        name: 'specificData.dataHandling.dataEncryptionInTransit',
        label: 'Is data encrypted in transit (TLS/SSL)?',
        type: 'radio',
        required: true,
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'no', label: 'No' },
        ],
      },
      {
        name: 'specificData.dataHandling.gdprCompliant',
        label: 'Are you GDPR compliant (if applicable)?',
        type: 'radio',
        required: false,
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'no', label: 'No' },
          { value: 'in-progress', label: 'In Progress' },
          { value: 'na', label: 'Not Applicable' },
        ],
      },
      {
        name: 'specificData.dataHandling.ccpaCompliant',
        label: 'Are you CCPA compliant (California)?',
        type: 'radio',
        required: false,
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'no', label: 'No' },
          { value: 'in-progress', label: 'In Progress' },
          { value: 'na', label: 'Not Applicable' },
        ],
      },
      {
        name: 'specificData.dataHandling.dataRetentionPolicy',
        label: 'Do you have a data retention policy?',
        type: 'radio',
        required: true,
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'no', label: 'No' },
        ],
      },
    ],
  },
  {
    id: 'security',
    title: 'Security Measures',
    description: 'What security practices do you follow?',
    fields: [
      {
        name: 'specificData.securityMeasures.hasSecurityPolicy',
        label: 'Do you have a written information security policy?',
        type: 'radio',
        required: true,
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'no', label: 'No' },
        ],
      },
      {
        name: 'specificData.securityMeasures.hasCISO',
        label: 'Do you have a dedicated CISO or security team?',
        type: 'radio',
        required: true,
        options: [
          { value: 'yes-internal', label: 'Yes - Internal' },
          { value: 'yes-outsourced', label: 'Yes - Outsourced/Virtual CISO' },
          { value: 'no', label: 'No' },
        ],
      },
      {
        name: 'specificData.securityMeasures.hasPenetrationTesting',
        label: 'Do you conduct regular penetration testing?',
        type: 'radio',
        required: true,
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'no', label: 'No' },
        ],
      },
      {
        name: 'specificData.securityMeasures.penTestFrequency',
        label: 'Penetration Testing Frequency',
        type: 'select',
        required: false,
        options: [
          { value: 'quarterly', label: 'Quarterly' },
          { value: 'semi-annual', label: 'Semi-Annual' },
          { value: 'annual', label: 'Annual' },
          { value: 'as-needed', label: 'As Needed' },
        ],
      },
      {
        name: 'specificData.securityMeasures.hasVulnerabilityScanning',
        label: 'Do you perform regular vulnerability scanning?',
        type: 'radio',
        required: true,
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'no', label: 'No' },
        ],
      },
      {
        name: 'specificData.securityMeasures.hasSecurityAudit',
        label: 'Do you have third-party security audits (SOC 2, ISO 27001, etc.)?',
        type: 'radio',
        required: true,
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'no', label: 'No' },
          { value: 'in-progress', label: 'In Progress' },
        ],
      },
      {
        name: 'specificData.securityMeasures.securityCertifications',
        label: 'Security Certifications Held',
        type: 'textarea',
        required: false,
        placeholder: 'e.g., SOC 2 Type II, ISO 27001, FedRAMP, etc.',
      },
      {
        name: 'specificData.securityMeasures.hasMFA',
        label: 'Is Multi-Factor Authentication (MFA) enabled for all users?',
        type: 'radio',
        required: true,
        options: [
          { value: 'yes-all', label: 'Yes - All users' },
          { value: 'yes-admin', label: 'Yes - Admin/privileged users only' },
          { value: 'optional', label: 'Optional' },
          { value: 'no', label: 'No' },
        ],
      },
      {
        name: 'specificData.securityMeasures.hasIncidentResponsePlan',
        label: 'Do you have an incident response plan?',
        type: 'radio',
        required: true,
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'no', label: 'No' },
        ],
      },
      {
        name: 'specificData.securityMeasures.hasSecurityTraining',
        label: 'Do employees receive security awareness training?',
        type: 'radio',
        required: true,
        options: [
          { value: 'yes-regular', label: 'Yes - Regular/Annual' },
          { value: 'yes-onboarding', label: 'Yes - At onboarding only' },
          { value: 'no', label: 'No' },
        ],
      },
      {
        name: 'specificData.securityMeasures.hasEndpointProtection',
        label: 'Do you have endpoint protection (antivirus/EDR) on all devices?',
        type: 'radio',
        required: true,
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'partial', label: 'Partially' },
          { value: 'no', label: 'No' },
        ],
      },
    ],
  },
  {
    id: 'development',
    title: 'Development Practices',
    description: 'Tell us about your development and quality processes',
    fields: [
      {
        name: 'specificData.developmentPractices.hasQA',
        label: 'Do you have a dedicated QA/testing process?',
        type: 'radio',
        required: true,
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'no', label: 'No' },
        ],
      },
      {
        name: 'specificData.developmentPractices.hasStagingEnvironment',
        label: 'Do you use staging/testing environments before production?',
        type: 'radio',
        required: true,
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'no', label: 'No' },
        ],
      },
      {
        name: 'specificData.developmentPractices.codeReviewProcess',
        label: 'Is code review required before deployment?',
        type: 'radio',
        required: true,
        options: [
          { value: 'yes-all', label: 'Yes - All code' },
          { value: 'yes-some', label: 'Yes - Some code' },
          { value: 'no', label: 'No' },
        ],
      },
      {
        name: 'specificData.developmentPractices.automatedTesting',
        label: 'Do you use automated testing?',
        type: 'radio',
        required: true,
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'partial', label: 'Partially' },
          { value: 'no', label: 'No' },
        ],
      },
      {
        name: 'specificData.developmentPractices.hasVersionControl',
        label: 'Do you use version control (Git, etc.)?',
        type: 'radio',
        required: true,
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'no', label: 'No' },
        ],
      },
      {
        name: 'specificData.developmentPractices.hasSecureSDLC',
        label: 'Do you follow a Secure Software Development Lifecycle (SSDLC)?',
        type: 'radio',
        required: true,
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'partial', label: 'Partially' },
          { value: 'no', label: 'No' },
        ],
      },
      {
        name: 'specificData.developmentPractices.opensourcePolicy',
        label: 'Do you have a policy for using open-source components?',
        type: 'radio',
        required: true,
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'no', label: 'No' },
        ],
      },
      {
        name: 'specificData.developmentPractices.opensourceScanning',
        label: 'Do you scan open-source dependencies for vulnerabilities?',
        type: 'radio',
        required: false,
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'no', label: 'No' },
        ],
      },
    ],
  },
  {
    id: 'contracts',
    title: 'Client Contracts & Liability',
    description: 'Information about your client agreements',
    fields: [
      {
        name: 'specificData.clientContracts.hasWrittenContracts',
        label: 'Do you use written contracts with all clients?',
        type: 'radio',
        required: true,
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'most', label: 'Most clients' },
          { value: 'some', label: 'Some clients' },
          { value: 'no', label: 'No' },
        ],
      },
      {
        name: 'specificData.clientContracts.hasIndemnificationClauses',
        label: 'Do your contracts include limitation of liability clauses?',
        type: 'radio',
        required: true,
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'some', label: 'In some contracts' },
          { value: 'no', label: 'No' },
        ],
      },
      {
        name: 'specificData.clientContracts.liabilityCapMultiple',
        label: 'Typical Liability Cap',
        type: 'select',
        required: true,
        options: [
          { value: 'fees-paid', label: 'Fees paid under contract' },
          { value: '1x-annual', label: '1x annual contract value' },
          { value: '2x-annual', label: '2x annual contract value' },
          { value: 'fixed-amount', label: 'Fixed dollar amount' },
          { value: 'no-cap', label: 'No liability cap' },
          { value: 'varies', label: 'Varies by contract' },
        ],
      },
      {
        name: 'specificData.clientContracts.typicalContractValue',
        label: 'Typical Annual Contract Value (USD)',
        type: 'currency',
        required: true,
        placeholder: '50000',
        helperText: 'Average annual value of your client contracts',
      },
      {
        name: 'specificData.clientContracts.largestContractValue',
        label: 'Largest Single Contract Value (USD)',
        type: 'currency',
        required: true,
        placeholder: '250000',
        helperText: 'Value of your largest current client contract',
      },
      {
        name: 'specificData.clientContracts.hasHoldHarmless',
        label: 'Are you required to sign hold harmless/indemnification agreements?',
        type: 'radio',
        required: true,
        options: [
          { value: 'yes-often', label: 'Yes - Often' },
          { value: 'yes-sometimes', label: 'Yes - Sometimes' },
          { value: 'no', label: 'No' },
        ],
      },
      {
        name: 'specificData.clientContracts.hasInsuranceRequirements',
        label: 'Do clients require you to carry specific insurance?',
        type: 'radio',
        required: true,
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'sometimes', label: 'Sometimes' },
          { value: 'no', label: 'No' },
        ],
      },
    ],
  },
  {
    id: 'prior-incidents',
    title: 'Prior Incidents & Circumstances',
    description: 'Disclosure of any known issues',
    fields: [
      {
        name: 'specificData.priorIncidents.hasPriorClaims',
        label: 'Have you had any E&O claims in the past 5 years?',
        type: 'radio',
        required: true,
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'no', label: 'No' },
        ],
      },
      {
        name: 'specificData.priorIncidents.claimsDetails',
        label: 'If yes, please describe (date, nature, outcome, amount)',
        type: 'textarea',
        required: false,
        placeholder: 'Provide details about each claim...',
      },
      {
        name: 'specificData.priorIncidents.hasKnownCircumstances',
        label: 'Are you aware of any circumstances that could give rise to a claim?',
        type: 'radio',
        required: true,
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'no', label: 'No' },
        ],
      },
      {
        name: 'specificData.priorIncidents.circumstancesDetails',
        label: 'If yes, please describe the circumstances',
        type: 'textarea',
        required: false,
        placeholder: 'Describe any potential issues...',
      },
      {
        name: 'specificData.priorIncidents.hasDataBreach',
        label: 'Have you experienced a data breach in the past 5 years?',
        type: 'radio',
        required: true,
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'no', label: 'No' },
        ],
      },
      {
        name: 'specificData.priorIncidents.dataBreachDetails',
        label: 'If yes, please describe the breach',
        type: 'textarea',
        required: false,
        placeholder: 'Include date, number of records affected, and remediation steps taken...',
      },
      {
        name: 'specificData.priorIncidents.hasLitigation',
        label: 'Are you currently involved in any litigation?',
        type: 'radio',
        required: true,
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'no', label: 'No' },
        ],
      },
      {
        name: 'specificData.priorIncidents.litigationDetails',
        label: 'If yes, please describe the litigation',
        type: 'textarea',
        required: false,
        placeholder: 'Describe the nature of the litigation...',
      },
    ],
  },
];

export const techEOConfig: InsuranceTypeConfig = {
  id: 'tech-eo',
  name: 'Technology E&O',
  description: 'Errors & Omissions coverage for technology companies',
  icon: 'Globe',
  commonSteps: commonSteps,
  specificSteps: techEOSpecificSteps,
};
